server:
  port: 8082
  servlet:
    context-path: '/ead-course/'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
          lob.non-contextual-creation: true
      properties:
        hibernate:
          show_sql: true
  output:
    ansi:
      enabled: always

ead:
  api:
    url:
      authuser: 'http://localhost:8087/ead-authuser'

logging:
  level:
    com.ead: trace
    root: info
    org.springframework.web: debug
    org.hibernate: info